FIND_PATH(VT_INCLUDE_DIR
    NAMES
        vt/VirtualTexture.h
    PATHS
        "$ENV{VT_DIR}/include/"
)

MESSAGE(STATUS "VT_LIBRARY_DEBUG PRE: ${VT_LIBRARY_DEBUG}")
		
FIND_LIBRARY(VT_LIBRARY_DEBUG
	NAMES
		LibVTD.lib
		vt_debug.lib
        vt_debug
	PATHS
        "$ENV{VT_DIR}"
)

MESSAGE(STATUS "VT_LIBRARY_DEBUG POST: ${VT_LIBRARY_DEBUG}")

FIND_LIBRARY(VT_LIBRARY_RELEASE
	NAMES
		LibVT.lib
		vt.lib
		vt
	PATHS
        "$ENV{VT_DIR}"
)

SET( VT_FOUND "NO" )
IF( VT_LIBRARY_RELEASE AND VT_INCLUDE_DIR )

    SET( VT_FOUND "YES" )
    SET( VT_INCLUDE_DIRS ${VT_INCLUDE_DIR} )
	
	IF(VT_LIBRARY_DEBUG)
        SET( VT_LIBRARIES optimized ${VT_LIBRARY_RELEASE} debug ${VT_LIBRARY_DEBUG} )
    ELSE(VT_LIBRARY_DEBUG)
        SET( VT_LIBRARIES ${VT_LIBRARY_RELEASE} )
        MESSAGE(WARNING "-- Warning Debug VT not found, using: ${VT_LIBRARY_RELEASE}")
    ENDIF(VT_LIBRARY_DEBUG)
ENDIF( VT_LIBRARY_RELEASE AND VT_INCLUDE_DIR )
